## Package Import

In [1]:
%load_ext autoreload
%autoreload 2
from final_deliverable.utils_final import *

***
## <center> Before Everything
This notebook is aimed for the data pipeline in order to be compatible with the classifiers (ranking step), MVO (weighting step),and backtest pipelines. For more details on how we visualized and manipulated the broad assets weekly, equity domestic baskets, and equity global baskets monthly data, please refer to the `initial_analysis.ipynb` notebook (i.e., section `Initial Visualizations`, `Aggregating Returns up to Weekly`, and `Aggregating Returns up to Monthly`) and `utils.py`. Now, we would like to use the following data in construction the data pipeline in prepare to feed our classifiers (note that all of the directories for the data below are under `/data`):
1. broad assets (11 assets in total) daily returns: `broad_assets` from `fpi_raw_data.xlsx` first sheet
2. broad assets **weekly returns**: `weekly_rets` from `broad_assets_weekly_rets.xlsx`
3. equity domestic baskets (46 assets in total) daily returns: `equity_domestic` from `fpi_raw_data.xlsx` second sheet
4. equity domestic baskets **monthly returns**: `equity_domestic_monthly_rets` from `equity_domestic_monthly_rets.xlsx`
5. equity global baskets (52 assets in total) daily returns: `equity_global` from `fpi_raw_data.xlsx` third sheet
6. equity global baskets **monthly returns**: `equity_global_monthly_rets` from `equity_global_monthly_rets.xlsx`:
***

## Universe of Broad Assets Daily Returns Import

In [2]:
data_path = os.path.dirname(os.getcwd()) + '/data'
data_file = data_path + '/fpi_raw_data.xlsx'
data = pd.read_excel(data_file, sheet_name='Universe of broad assets', index_col=0, parse_dates=True)
broad_assets = data.copy()
broad_assets

,Asset 1,Asset 2,Asset 3,Asset 4,Asset 5,Asset 6,Asset 7,Asset 8,Asset 9,Asset 10,Asset 11
Date,,,,,,,,,,,
2000-07-31,0.0152,0.0757,-0.0023,0.0009,0.0422,0.0050,0.0373,0.0021,-0.0025,-0.0084,-0.0318
2000-08-01,0.0099,-0.0491,0.0079,0.0063,-0.0115,0.0404,-0.0292,0.0107,0.0096,0.0005,0.0146
2000-08-02,0.0007,-0.0178,0.0015,0.0037,0.0098,-0.0095,-0.0005,0.0010,0.0112,0.0012,0.0187
2000-08-03,0.0192,0.0761,0.0072,0.0031,-0.0031,-0.0210,-0.0307,-0.0095,0.0061,-0.0262,0.0072
2000-08-04,0.0142,-0.0030,0.0066,0.0062,0.0164,-0.0249,0.0129,0.0042,-0.0012,-0.0036,0.0326
...,...,...,...,...,...,...,...,...,...,...,...
2024-08-30,0.0203,0.0258,-0.0144,-0.0047,0.0135,0.0194,0.0043,0.0039,0.0070,-0.0145,-0.0239
2024-09-03,-0.0423,-0.0631,0.0225,0.0078,-0.0618,0.0019,-0.0384,-0.0399,0.0028,-0.0086,-0.0392
2024-09-04,-0.0033,-0.0040,0.0250,0.0097,-0.0039,0.0043,-0.0051,-0.0007,-0.0092,0.0020,-0.0186
2024-09-05,-0.0062,0.0009,0.0153,0.0034,-0.0123,-0.0059,-0.0051,0.0026,-0.0045,0.0167,0.0044
2024-09-06,-0.0345,-0.0537,0.0022,0.0050,-0.0381,-0.0007,-0.0301,-0.0369,0.0014,-0.0156,-0.0279

## Universe of Broad Assets Weekly Returns Import

In [3]:
data_path = os.path.dirname(os.getcwd()) + '/data'
data_prefix = '/broad_assets_'
weekly_rets_file = data_path + data_prefix + 'weekly_rets.xlsx'
weekly_rets = pd.read_excel(weekly_rets_file, index_col=0)
weekly_rets

,Asset 1,Asset 2,Asset 3,Asset 4,Asset 5,Asset 6,Asset 7,Asset 8,Asset 9,Asset 10,Asset 11
Date,,,,,,,,,,,
2000-07-31,0.0152,0.0757,-0.0023,0.0009,0.0422,0.0050,0.0373,0.0021,-0.0025,-0.0084,-0.0318
2000-08-07,0.0679,0.0526,0.0159,0.0134,0.0365,-0.0237,-0.0196,-0.0116,0.0241,-0.0266,0.0346
2000-08-14,0.0157,0.0023,0.0152,0.0063,0.0171,0.0254,0.0294,0.0369,0.0085,0.0063,0.0481
2000-08-21,0.0095,0.0566,-0.0018,-0.0003,0.0068,-0.0264,0.0016,-0.0024,0.0077,0.0018,0.0384
2000-08-28,0.0184,0.0653,0.0019,0.0041,0.0379,-0.0353,0.0195,-0.0170,0.0019,-0.0095,0.0313
...,...,...,...,...,...,...,...,...,...,...,...
2024-08-12,0.0607,0.0718,-0.0440,-0.0147,0.0210,0.0425,0.0431,0.0882,0.0093,0.0503,0.0583
2024-08-19,0.1006,0.1346,0.0199,-0.0004,0.1037,0.0321,0.0931,0.0771,-0.0238,0.0239,-0.0377
2024-08-26,0.0020,-0.0266,0.0028,0.0064,0.0450,0.0540,0.0290,-0.0180,-0.0195,0.0097,0.0332
2024-08-30,0.0108,0.0050,-0.0310,-0.0094,-0.0007,0.0091,0.0127,-0.0055,0.0175,-0.0126,-0.0348
2024-09-06,-0.0841,-0.1162,0.0664,0.0261,-0.1122,-0.0004,-0.0769,-0.0735,-0.0095,-0.0057,-0.0793

***
## Equity Domestic / Equity Global Daily Returns Import

In [4]:
equity_domestic = pd.read_excel(data_file, sheet_name='Equity factor baskets domestic', index_col=0, parse_dates=True)
equity_global = pd.read_excel(data_file, sheet_name='Equity factor baskets global', index_col=0, parse_dates=True)
display(equity_domestic.head(), equity_global.head())

,Asset 1,Asset 2,Asset 3,Asset 4,Asset 5,Asset 6,Asset 7,Asset 8,Asset 9,Asset 10,...,Asset 37,Asset 38,Asset 39,Asset 40,Asset 41,Asset 42,Asset 43,Asset 44,Asset 45,Asset 46
Date,,,,,,,,,,,,,,,,,,,,,
2001-01-03,NaN,NaN,NaN,-0.0338,NaN,NaN,NaN,-0.0137,NaN,NaN,...,0.0115,0.0419,0.0675,0.1113,0.0419,0.0177,-0.0411,-0.0118,-0.0171,-0.0013
2001-01-04,NaN,NaN,NaN,-0.0471,NaN,NaN,NaN,-0.0047,NaN,NaN,...,-0.0255,-0.0447,-0.0019,-0.0247,-0.0155,-0.0034,-0.0719,0.0072,0.0065,0.0030
2001-01-05,NaN,NaN,NaN,0.0231,NaN,NaN,NaN,-0.0008,NaN,NaN,...,-0.0301,-0.0328,-0.0380,-0.0665,-0.0196,-0.0294,0.0054,0.0056,0.0046,0.0033
2001-01-08,NaN,NaN,NaN,0.0138,NaN,NaN,NaN,0.0089,NaN,NaN,...,0.0027,0.0025,-0.0007,0.0115,0.0050,-0.0092,0.0179,0.0027,0.0003,0.0014
2001-01-09,NaN,NaN,NaN,-0.0126,NaN,NaN,NaN,-0.0104,NaN,NaN,...,0.0041,-0.0077,0.0324,0.0113,-0.0091,0.0082,-0.0093,-0.0039,-0.0026,-0.0018

,Asset 1,Asset 2,Asset 3,Asset 4,Asset 5,Asset 6,Asset 7,Asset 8,Asset 9,Asset 10,...,Asset 43,Asset 44,Asset 45,Asset 46,Asset 47,Asset 48,Asset 49,Asset 50,Asset 51,Asset 52
Date,,,,,,,,,,,,,,,,,,,,,
2003-04-14,0.0059,0.0035,NaN,0.0069,NaN,NaN,0.0090,0.0042,NaN,NaN,...,NaN,NaN,NaN,-0.0027,-0.0008,-0.0028,NaN,NaN,0.0207,0.0204
2003-04-15,0.0391,0.0270,NaN,0.0248,NaN,NaN,0.0125,0.0180,NaN,NaN,...,NaN,NaN,NaN,0.0054,0.0007,0.0035,NaN,NaN,0.0093,0.0096
2003-04-16,0.0190,0.0071,NaN,0.0045,NaN,NaN,0.0018,-0.0116,NaN,NaN,...,NaN,NaN,NaN,0.0041,0.0001,0.0022,NaN,NaN,-0.0170,-0.0023
2003-04-17,0.0197,0.0233,NaN,0.0125,NaN,NaN,-0.0024,0.0187,NaN,NaN,...,NaN,NaN,NaN,0.0016,-0.0008,-0.0013,NaN,NaN,0.0148,0.0229
2003-04-21,0.0028,0.0441,NaN,0.0248,NaN,NaN,0.0097,0.0130,NaN,NaN,...,NaN,NaN,NaN,-0.0022,0.0006,-0.0019,NaN,NaN,0.0010,0.0037

## Equity Domestic / Equity Global Monthly Returns Import

In [5]:
equity_domestic_monthly_rets = pd.read_excel(data_path + '/equity_domestic_monthly_rets.xlsx', index_col=0, parse_dates=True)
equity_global_monthly_rets = pd.read_excel(data_path + '/equity_global_monthly_rets.xlsx', index_col=0, parse_dates=True)
display(equity_domestic_monthly_rets.head(), equity_global_monthly_rets.head())

,Asset 1,Asset 2,Asset 3,Asset 4,Asset 5,Asset 6,Asset 7,Asset 8,Asset 9,Asset 10,...,Asset 37,Asset 38,Asset 39,Asset 40,Asset 41,Asset 42,Asset 43,Asset 44,Asset 45,Asset 46
Date,,,,,,,,,,,,,,,,,,,,,
2001-01-03,0.0000,0.0000,0.0000,-0.0338,0.0000,0.0000,0.0000,-0.0137,0.0000,0.0000,...,0.0115,0.0419,0.0675,0.1113,0.0419,0.0177,-0.0411,-0.0118,-0.0171,-0.0013
2001-02-01,0.0000,0.0000,0.0000,-0.0378,0.0000,0.0000,0.0000,0.0048,0.0000,0.0000,...,0.0166,0.0215,-0.0046,0.0319,0.0253,-0.0520,-0.0496,0.0120,0.0114,0.0100
2001-03-01,0.0000,0.0000,0.0000,0.0269,0.0000,0.0000,0.0000,0.0441,0.0000,0.0000,...,-0.0172,0.0704,0.0395,-0.1746,0.0087,0.0011,0.0999,0.0110,0.0135,0.0058
2001-04-02,0.0000,0.0000,0.0000,-0.0210,0.0000,0.0000,0.0000,0.0367,0.0000,0.0000,...,-0.0038,-0.0238,-0.0028,-0.1542,-0.0019,-0.0201,0.0181,0.0008,-0.0176,0.0081
2001-05-01,0.0000,0.0000,0.0000,0.0414,0.0000,0.0000,0.0000,0.0314,0.0000,0.0000,...,0.0053,0.1430,0.0607,0.2815,0.0649,0.0244,0.0337,-0.0122,-0.0239,0.0032

,Asset 1,Asset 2,Asset 3,Asset 4,Asset 5,Asset 6,Asset 7,Asset 8,Asset 9,Asset 10,...,Asset 43,Asset 44,Asset 45,Asset 46,Asset 47,Asset 48,Asset 49,Asset 50,Asset 51,Asset 52
Date,,,,,,,,,,,,,,,,,,,,,
2003-04-14,0.0059,0.0035,0.0000,0.0069,0.0000,0.0000,0.0090,0.0042,0.0000,0.0000,...,0.0000,0.0000,0.0000,-0.0028,-0.0009,-0.0028,0.0000,0.0000,0.0207,0.0204
2003-05-01,0.1023,0.1299,0.0000,0.0811,0.0000,0.0000,0.0997,0.0606,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0328,0.0056,0.0169,0.0000,0.0000,0.0332,0.0638
2003-06-02,0.0422,0.3734,0.0000,0.1223,0.0000,0.0000,0.1478,0.2189,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0603,0.0047,0.0370,0.0000,0.0000,0.0593,0.0683
2003-07-01,0.1001,0.1734,0.0000,0.0544,0.0000,0.0000,0.0618,0.1381,0.0000,0.0000,...,0.0000,0.0000,0.0000,-0.0115,0.0035,-0.0025,0.0000,0.0000,0.0158,0.0260
2003-08-01,0.0754,0.1196,0.0000,-0.0382,0.0000,0.0000,0.0560,0.0665,0.0000,0.0000,...,0.0000,0.0000,0.0000,-0.0922,-0.0049,-0.0515,0.0000,0.0000,-0.0002,0.0366

***
## <center> Indicators Construction

### General Idea on Broad Asset Universe

For the broad asset universe, we are going to construct $52$ momentum-and-risk-related indicators and another $52*5 = 260$ lagged features on these $52$ basic indicators. So the total amount of indicators for each basket is $312$. Besides this, we added $11$ one-hot encoding binary variables based on the number of assets in the current universe. We have the most complete dataset for each 11 asset starting from the original return data compared with other two. The final feature datasets are asset-wise, containing 312 columns in total. We merged the data based on the most available dates each feature had, so the starting date would subject to shrink from original data (i.e., 2000-07-31) to the current data (i.e., 2002-10-28).

### General Ideas on Equity Domestic Basket & Equity Global Basket

The construction logics of building indicators for these two equity baskets are $90\%$ similar with that of broad asset universe. To be more specific, we made the following adjustment (<span style="color:blue">kudos to Sam here®</span>): Since return data for each asset has different earliest available date, we created an outer loop to handle the missing values and then calculated the indicator specific to each asset. Also, one-hot encoding procedure and the downside devaition calculation have both been moved into this outer loop section as well to make the production as expected. For the equity domestic and global baskets, we still had $52$ features and $52*5 = 260$ ($312$ features in total). Hence, the final number of features for the equity domestic basket is $358$ (plus $46$ one-hot encoding variables) and for the equity global basket is $364$ (plus $52$ one-hot encoding variables). Due to various earliest start dates for each asset, the final feature datasets would subject to shrink more than the broad asset features. For Equity Domestic Basket, the start date from the final data shrunk from 2001-01-03 (start date from the original data) to 2008-04-01. For Equity Global Basket, the start date from the final data shrunk from 2003-04-14 to 2006-05-01. But thanks to the classifier ranking step, we stack all of the data to form a huge dataset by weakening the concept of so-called “asset” (which will be introduced in the `classifier_model2.ipynb` so that we should be less concerned about the insufficient data reduction in this specific case.

Below, we will narrow down to each indicator (i.e., from the momentum, risk and drawdown aspects) intro.

1. **ROC (Rate of Change):** ROC compares the current price (via returns) to a past price (via compounded returns over the window). Positive values indicate upward momentum (gains), while negative values indicate downward momentum (losses). We calculated it as follows: $$ROC_t = \prod_{i=1}^n (1+r_i)-1$$

- For the weekly data in the broad assets, we would like to use 4, 6, 12, 26, 52-week ROC to capture momentum across short-term and long-term horizons.
- For the monthly data in the equity domestic / global assets, we would like to use 1, 3, 6, 9, 12-month ROC to capture momentum.

<span style="color:red">Note that ROC is the only indicator which will use the weekly / monthly returns data (other indicators all require to use the daily returns), we would calculate the ROC indicator outside the `apply_indicator` function by running the for loop to get the ROC for each asset. </span>

***

<span style="color:blue">Below the section, all the calculations for the rest of the indicators are completed within the `apply_indicator` function using the daily data only for different baskets.</span>

2. **MACD Line, Signal Line, and MACD Histogram:**
$$
\text{MACD Line} = \text{EMA}_{short} - \text{EMA}_{long}
$$

$$
\text{Signal Line} = \text{EMA}_{signal\,period}
$$

$$
\text{MACD Histogram} = \text{MACD Line} - \text{Signal Line}
$$
In this case, we tried the general one, in which we set the short-period as 12 days, long-period as 26 days, and signal period as 9 days.
- The MACD Line: This accounts for the change in momentum through the relation of short-term versus long-term trends. A positive MACD represents upward momentum, while a negative MACD represents downward momentum.
- Crossovers between the MACD Line and Signal Line act as buy/sell signals:
    - Bullish Crossover: The point at which the MACD Line crosses over the Signal Line.
    - Bearish Crossover: When the MACD Line crosses below the Signal Line.
- The MACD Histogram: focuses on the magnitude and direction of changes in momentum. An expanding histogram indicates strengthening momentum, while a shrinking histogram signals weakening momentum.

***
3. **RSI (Relative Strength Index) & Stochastic RSI:** RSI measures the relative strength of gains compared to losses, which indicates overbought or oversold conditions in an asset. Stochastic RSI enhances RSI by normalizing its values within a fixed range (0–1) and provides clearer signals in volatile markets.
First, we convert daily returns to cumulative price series:
$$
\text{price data}_t = \prod_{i=1}^n (1+r_i)
$$
Then we calculated the daily price changes $\Delta_t$. For positive price changes, we set negative changes to 0; For neagtive price changes, we absolute the values and set positive changes to 0. Compute the rolling average of gains and losses over the specified window period.
$$
\text{gain}_t = \text{loss}_t = \Delta_t = \text{price data}_t - \text{price data}_{t-1}
$$

$$
\text{average gain}_t = \frac{1}{\text{window}}\sum_{i=0}^{\text{window}-1}\text{gain}_{t-i}
$$

$$
\text{average loss}_t = \frac{1}{\text{window}}\sum_{i=0}^{\text{window}-1}\text{loss}_{t-i}
$$
The relative strength is then calculated to measure the ratio of average gains to average losses.
$$
\text{RS}_t = \frac{\text{average gain}_t}{\text{average loss}_t}
$$
The RSI is computed from RS using the following formula:
$$
\text{RSI}_t = 100 - \frac{100}{1+\text{RS}_t}
$$
- RSI values range from 0 to 100.
- $\text{RSI} > 70$: Asset is considered overbought (potential sell signal).
- $\text{RSI} < 30$: Asset is considered oversold (potential buy signal).

The Stochastic RSI can also be calculated by normalizing RSI values between 0 and 1 by comparing the RSI to its historical minimum and maximum over the rolling window:
$$
\text{Stoch RSI}_t = \frac{\text{RSI}_t - min(\text{RSI}_{t-window:t})}{max(\text{RSI}_{t-window:t}) - min(\text{RSI}_{t-window:t})}
$$
- $\text{Stoch RSI} > 0.8$: Overbought conditions.
- $\text{Stoch RSI} < 0.2$: Oversold conditions.

We leveraged 14-day (half a month) window to evaluate the RSI for each asset.

***

4. **Bollinger Bands (SMA, Upper, and Lower Bands):** Bollinger Bands can be effectively used as momentum indicators as we may observe a strong upward momentum when prices repeatedly touch or exceed the upper band, and vice versa. In another aspect, we can attain some of the volatility insights from it. In other words, a narrower band would always indicates lower volatility, which often preceds significant price movements.

In this implementation, we would opt 20, 90, 180, and 240-day as our rolling window sizes to perform the following bands calculations. For the rolling window size $N$:

We can calculate the simple moving average (SMA):
$$
\text{SMA}_N = \frac{1}{N}\sum_{i = t-N+1}^t P_i
$$

With SMA, it's easy for us to calculate the rolling standard deviation (SD):

$$
\text{SD}_N = \sqrt{\frac{1}{N}\sum_{i = t-N+1}^t (P_i - \text{SMA}_N)^2}
$$

It's easy for us to derive the Upper and Lower Bollinger Bands:
$$
\text{Upper}_N = \text{SMA}_N + \text{num\_std} \times \text{SD}_N
$$

$$
\text{Lower}_N = \text{SMA}_N - \text{num\_std} \times \text{SD}_N
$$

Where:
- $P_i$ is the price at time $i$, which has been converted by the returns data through `.cumprod()`.
- $N$ is the rolling window size.
- $\text{num\_std}$ is the number of standard deviations used (commonly 2).

***

5. **Hilbert Transform (DCPERIOD, DCPHASE, PHASOR, SINE, TRENDMODE)**: We also leveraged the convenience provided by `TA-Lib.HT` method to extract information about the instantaneous amplitude, phase, and frequency of a signal.

- Dominant Cycle Period (`HT_DCPERIOD`): Identifies the dominant cycle length in the price series to gauge the periodicity of market behavior.
- Dominant Cycle Phase (`HT_DCPHASE`): Measures the phase of the dominant cycle to provide insights into the cycle’s current position (e.g., peak, trough).
- Phasor Components (`HT_PHASOR`): Outputs in-phase and quadrature components to track the real-time cyclic structure of the time series.
- SineWave (`HT_SINE`): Generates sine and lead sine components to identify potential inflection points in market cycles.
- Trend vs Cycle Mode (`HT_TRENDMODE`): Distinguishes between trending and cyclic market conditions.

***

6. **EWMA (Exponentially Weighted Moving Average) Volatility:** We would like to substitute the traditional volatilities with the EWMA volatility by giving more weight to recent data while gradually discounting older observations with a decay factor (smoothing parameter, $\theta$), which would be more useful in rapidly changing markets. Besides filtering assets by momentum factors, we also want to guarantee the volatility of selecting assets considerable. On the other hands, changes in EWMA volatility can also signal potential momentum breakouts: Sudden increases in volatility often precede significant price movements. Stable, low EWMA volatility can indicate consolidation phases, while high volatility reflects turbulent periods.

In this case, we would set our initial variance as $\sigma_0^2 = (\frac{0.2}{\sqrt{252}})^2$. Then, we are able to evaluate the next-phase variance (and thus the volatility) using the previous-determined variance, $\sigma_{t-1}^2$ and the current-phase return $r_t$:

$$
\text{EWMA Volatility} = \sqrt{\sigma_t^2} = \sqrt{\theta \sigma_{t-1}^2 + (1-\theta)r_t^2}
$$

***

7. **Rolling Volatility / Rolling & Expanding Skew / Rolling & Expanding Kurtosis:** 
- High rolling volatility may indicate increased asset uncertainty; stable one suggests stable market conditions.
- Persistent negative rolling skewness suggests a greater likelihood of extreme negative returns (which would capture downside risk that momentums do not capture).
- High rolling kurtosis in conjunction with rising volatility may indicate potential asset instability.

The combination of these indicators would provide us a clearer regime identification for better asset allocation advise.
For rolling, we provided 20, 60, 126, 252, and 504-day windows to calculate metrics for comprehensive monitoring of short vs. long-term changes.

***

8. **Downside Deviation**: We also want to include this feature to quantify the standard deviation of negative asset returns relative to a specified target return (In default, we would like to set it as 0% and can be set to something positive if we really want to be more stringent). For each rolling window size in rolling_windows, the function calculates the downside deviation as:
$$
\text{Downside Deviation} = \sqrt{\frac{1}{n} \sum_{i=1}^{n} \min(x_i - \text{Target Return}, 0)^2}
$$
Unlike standard deviation, which considers all variability, downside deviation isolates downside risk, thereby aligning better with risk-averse investors' perspectives.

***

9. **Cumulative Drawdown Periods:** The drawdown period indicator measures the number of consecutive periods an asset remains in a drawdown state. A drawdown occurs when the asset's cumulative return falls below its previous peak value. This indicator provides insights into how long an asset stays in a drawdown, which can be a good indicator to unveil the persistence of unfavorable market conditions. Here, we compute cumulative returns for each asset and identify the cumulative maximum returns (peak values) up to each time point; Determine if the current return is below the peak value (in drawdown) and count the number of consecutive periods the asset remains in drawdown until a new peak is achieved.

***

10. **Drawdown Counts:** The drawdown count indicator tracks the cumulative number of distinct drawdowns an asset has experienced up to each time point. A distinct drawdown begins when the asset enters a drawdown state after reaching a new peak. Different from cumulative one, drawdown counts firstly computes cumulative returns and identify peak values up to each time point and detect transitions from non-drawdown (0) to drawdown (1); Increment the count for each new drawdown initiation and then aggregate the counts over time for a cumulative total.

***

11. **Lagged Indicators:** We also want to include the lagged momentum indicators — such as rolling volatility, skewness, kurtosis, or other measures with lags of 1, 2, 4, 6, and 12 periods to capture the evolution of momentum over time, if any. Lagged indicators allow for detecting the acceleration or deceleration of trends that traditional momentum cannot have. If momentum weakens at longer lags, it could signal a potential reversal. Conversely, consistent strength across lags may confirm a robust trend. We created a multiple lag periods to provide a temporal cross-validation for momentum signals to ensure that the trend is not isolated to a specific time frame.

***
## Asset-wise Feature DataFrame Output for Broad Assets

Adding all indicators from the function `apply_indicators_broad_assets` with ROC, we will get 11 data frames , each representing all of momentum indicators for one specific asset (with one-hot encoding binary, 1 for the correponding asset column, and 0 for the others). For reference, the 11 output excel files can be found in the `~/data` directory, each named with `broad_asset_n_features.xlsx`, where 'n' stands for the asset number.

In [6]:
roc_periods = [4, 6, 12, 26, 52]
asset_columns = [col for col in weekly_rets.columns if col.startswith('Asset')]

indicators = {
    'ROC': lambda df: calculate_roc(df, roc_periods)
}

asset_dataframes = apply_indicators_broad_assets(
    data=weekly_rets,             # Weekly returns data for each asset
    indicators=indicators,        # Dictionary of indicators
    assets=asset_columns,         # List of asset columns
    reference_data=broad_assets   # Daily return data for indicators calculation
)

asset_dataframes[asset_columns[0]]

,MACD_Line,Signal_Line,MACD_Histogram,RSI,Stoch_RSI,SMA20,SMA90,SMA180,SMA240,Upper20,...,Asset_2,Asset_3,Asset_4,Asset_5,Asset_6,Asset_7,Asset_8,Asset_9,Asset_10,Asset_11
Date,,,,,,,,,,,,,,,,,,,,,
2002-10-28,0.0067,0.0009,0.0058,68.4866,0.8951,0.3127,0.3499,0.4468,0.4815,0.3714,...,0,0,0,0,0,0,0,0,0,0
2002-11-04,0.0083,0.0052,0.0031,58.3816,0.3709,0.3264,0.3449,0.4410,0.4763,0.3802,...,0,0,0,0,0,0,0,0,0,0
2002-11-11,0.0073,0.0078,-0.0005,45.2142,0.0000,0.3427,0.3410,0.4357,0.4712,0.3647,...,0,0,0,0,0,0,0,0,0,0
2002-11-18,0.0059,0.0064,-0.0005,56.2893,0.4459,0.3455,0.3383,0.4293,0.4661,0.3648,...,0,0,0,0,0,0,0,0,0,0
2002-11-25,0.0097,0.0076,0.0022,55.9635,0.4966,0.3513,0.3390,0.4225,0.4613,0.3786,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-08-12,-0.1897,-0.1354,-0.0543,37.4974,0.6799,8.9749,8.6904,8.0864,7.5636,9.8747,...,0,0,0,0,0,0,0,0,0,0
2024-08-19,0.0200,-0.0798,0.0998,58.9321,1.0000,8.9141,8.7429,8.1629,7.6225,9.6944,...,0,0,0,0,0,0,0,0,0,0
2024-08-26,0.1371,0.0474,0.0897,80.0522,0.9280,9.0253,8.8285,8.2464,7.6900,9.9739,...,0,0,0,0,0,0,0,0,0,0
2024-08-30,0.1530,0.1066,0.0464,77.9372,0.7830,9.1347,8.9087,8.3108,7.7441,10.1585,...,0,0,0,0,0,0,0,0,0,0
2024-09-06,0.0328,0.0889,-0.0561,36.6557,0.0000,9.2940,8.9607,8.3588,7.7956,9.9191,...,0,0,0,0,0,0,0,0,0,0

## Data Export for 11 Broad Assets

In [7]:
data_path = os.path.dirname(os.getcwd()) + '/data'
os.makedirs(data_path, exist_ok=True)

# Export each asset DataFrame to an Excel file
for i, (asset, df) in enumerate(asset_dataframes.items(), start=1):
    filename = os.path.join(data_path, f'broad_asset_{i}_features.xlsx')
    df.to_excel(filename, sheet_name=f'{asset}_features', index=True)
    print(f"Exported {asset} to {filename}")

Exported Asset 1 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/broad_asset_1_features.xlsx
Exported Asset 2 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/broad_asset_2_features.xlsx
Exported Asset 3 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/broad_asset_3_features.xlsx
Exported Asset 4 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/broad_asset_4_features.xlsx
Exported Asset 5 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/broad_asset_5_features.xlsx
Exported Asset 6 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/broad_asset_6_features.xlsx
Exported Asset 7 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/broad_asset_7_features.xlsx
Exported Asset 8 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/broad_asset_8_features.xlsx
Exported Asset 9 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/broad_asset_9_features.xlsx
Exported Asset 10 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/broad_asset_10_features.xlsx
Exported Asset 11 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/broad_asset_11_features.xlsx

***
## Asset-wise Feature DataFrame Output for Equity Domestic / Global Baskets

To handle multiple N/A values for Equity Domestic & Global Baskets daily return data, we adjusted the function from `apply_indicators_broad_assets` to `apply_indicators_equity_baskets` by taking out the one-hot encoding part. Instead of directly calling the function, we would create an outer loop to drop the N/A values dynamically for each asset based on the length of its N/A value-period. In addition, we added the one-hot encoding asset columns to ensure the accurate implementation by adding the outer loop to iterate each asset. For reference, there are 46 output excel files for equity domestic assets and 52 output excel files for equity global assets in the `~/data` directory, named with `equity_domestic_n_features.xlsx` and `equity_global_n_features.xlsx`, respectively, where 'n' stands for the corresponding asset number for a specific basket.

In [8]:
roc_periods = [1, 3, 6, 9, 12]
lags = [1, 2, 4, 6, 12]
asset_columns = [col for col in weekly_rets.columns if col.startswith('Asset')]

indicators = {
    'ROC': lambda df: calculate_roc(df, roc_periods)
}

asset_dataframes_master_domestic = {}

for i_investment in range(equity_domestic_monthly_rets.shape[1]):
    data_in = pd.DataFrame(equity_domestic.iloc[:, i_investment]).dropna()
    equity_domestic_monthly_rets_in = pd.DataFrame(equity_domestic_monthly_rets.loc[data_in.index[0]:])
    columns_in = data_in.columns

    downside_deviation = calculate_downside_deviation_ts(
        data=data_in, 
        rolling_windows=[20, 60, 126, 252, 504], 
        target_return=0
    )

    asset_dataframes_out = apply_indicators_equity_baskets(
        data=equity_domestic_monthly_rets_in,           # Weekly returns data for each asset
        indicators=indicators,                          # Dictionary of indicators
        assets=columns_in,                              # List of asset columns
        reference_data=data_in                          # Daily return data for indicators calculation
    )

    for asset, asset_df in asset_dataframes_out.items():
        # Add downside deviation for the current asset
        if not downside_deviation.empty:
            downside_dev_cols = [col for col in downside_deviation.columns if asset in col]
            if downside_dev_cols:  # Only add columns if they exist for the current asset
                asset_df = pd.concat([asset_df, downside_deviation[downside_dev_cols]], axis=1)

        for lag in lags:
            lagged_downside_dev = downside_deviation[downside_dev_cols].shift(lag).add_suffix(f"_lag{lag}")
            asset_df = pd.concat([asset_df, lagged_downside_dev], axis=1)

        one_hot_df = pd.DataFrame(0, index=asset_df.index, 
                                  columns=[f'Asset_{i+1}' for i in range(equity_domestic_monthly_rets.shape[1])])
        one_hot_df[f'Asset_{i_investment + 1}'] = 1  # Set 1 only for the current asset being processed
        asset_df = pd.concat([asset_df, one_hot_df], axis=1)
        asset_df = asset_df.dropna()
        asset_df.columns = [col.replace(f'_{asset}', '') for col in asset_df.columns]
        asset_dataframes_out[asset] = asset_df
    asset_dataframes_master_domestic[i_investment] = asset_dataframes_out

i_investment = 0
asset_name = 'Asset 1'

asset_dataframes = asset_dataframes_master_domestic[i_investment]
final_asset_df = asset_dataframes['Asset 1']
final_asset_df

,MACD_Line,Signal_Line,MACD_Histogram,RSI,Stoch_RSI,SMA20,SMA90,SMA180,SMA240,Upper20,...,Asset_37,Asset_38,Asset_39,Asset_40,Asset_41,Asset_42,Asset_43,Asset_44,Asset_45,Asset_46
Date,,,,,,,,,,,,,,,,,,,,,
2008-04-01,-0.0104,-0.0125,0.0021,50.6904,0.9639,1.7538,1.8266,1.8663,1.8559,1.8741,...,0,0,0,0,0,0,0,0,0,0
2008-05-01,0.0457,0.0268,0.0190,84.3047,1.0000,1.8058,1.7957,1.8533,1.8597,1.9756,...,0,0,0,0,0,0,0,0,0,0
2008-06-02,0.0562,0.0531,0.0031,62.6678,0.5227,2.0427,1.8419,1.8820,1.8782,2.1623,...,0,0,0,0,0,0,0,0,0,0
2008-07-01,-0.0289,-0.0158,-0.0131,39.5492,0.5760,1.9997,1.8996,1.8884,1.8860,2.1632,...,0,0,0,0,0,0,0,0,0,0
2008-08-01,-0.0640,-0.0659,0.0019,28.6599,0.6976,1.7150,1.8850,1.8589,1.8729,1.8040,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-05-01,-0.0212,0.0104,-0.0316,28.8118,0.1722,6.3878,6.0081,5.5858,5.5684,6.6264,...,0,0,0,0,0,0,0,0,0,0
2024-06-03,0.0612,0.0475,0.0138,63.4588,0.3474,6.4941,6.2273,5.6954,5.6985,6.6577,...,0,0,0,0,0,0,0,0,0,0
2024-07-01,0.0212,0.0346,-0.0134,46.8002,0.0320,6.5699,6.4071,5.8479,5.7659,6.7106,...,0,0,0,0,0,0,0,0,0,0
2024-08-01,0.2032,0.1855,0.0177,57.5997,0.0000,7.0441,6.6065,6.1267,5.8738,7.7536,...,0,0,0,0,0,0,0,0,0,0
2024-08-30,0.0886,0.0760,0.0126,67.7571,0.8231,7.0306,6.7382,6.3482,6.0027,7.5024,...,0,0,0,0,0,0,0,0,0,0

In [9]:
data_path = os.path.dirname(os.getcwd()) + '/data'
os.makedirs(data_path, exist_ok=True)

for i_investment, asset_dataframes_out in asset_dataframes_master_domestic.items():
    for asset, df in asset_dataframes_out.items():
        filename = os.path.join(data_path, f'equity_domestic_{i_investment + 1}_features.xlsx')
        df.to_excel(filename, sheet_name=f'{asset}_features', index=True)
        print(f"Exported {asset} to {filename}")

Exported Asset 1 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_domestic_1_features.xlsx
Exported Asset 2 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_domestic_2_features.xlsx
Exported Asset 3 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_domestic_3_features.xlsx
Exported Asset 4 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_domestic_4_features.xlsx
Exported Asset 5 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_domestic_5_features.xlsx
Exported Asset 6 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_domestic_6_features.xlsx
Exported Asset 7 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_domestic_7_features.xlsx
Exported Asset 8 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_domestic_8_features.xlsx
Exported Asset 9 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_domestic_9_features.xlsx
Exported Asset 10 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_domestic_10_features.xlsx
Exported Asset 11 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_domestic_11_features.xlsx
Exported Asset 12 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_domestic_12_features.xlsx
Exported Asset 13 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_domestic_13_features.xlsx
Exported Asset 14 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_domestic_14_features.xlsx
Exported Asset 15 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_domestic_15_features.xlsx
Exported Asset 16 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_domestic_16_features.xlsx
Exported Asset 17 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_domestic_17_features.xlsx
Exported Asset 18 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_domestic_18_features.xlsx
Exported Asset 19 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_domestic_19_features.xlsx
Exported Asset 20 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_domestic_20_features.xlsx
Exported Asset 21 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_domestic_21_features.xlsx
Exported Asset 22 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_domestic_22_features.xlsx
Exported Asset 23 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_domestic_23_features.xlsx
Exported Asset 24 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_domestic_24_features.xlsx
Exported Asset 25 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_domestic_25_features.xlsx
Exported Asset 26 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_domestic_26_features.xlsx
Exported Asset 27 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_domestic_27_features.xlsx
Exported Asset 28 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_domestic_28_features.xlsx
Exported Asset 29 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_domestic_29_features.xlsx
Exported Asset 30 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_domestic_30_features.xlsx
Exported Asset 31 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_domestic_31_features.xlsx
Exported Asset 32 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_domestic_32_features.xlsx
Exported Asset 33 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_domestic_33_features.xlsx
Exported Asset 34 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_domestic_34_features.xlsx
Exported Asset 35 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_domestic_35_features.xlsx
Exported Asset 36 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_domestic_36_features.xlsx
Exported Asset 37 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_domestic_37_features.xlsx
Exported Asset 38 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_domestic_38_features.xlsx
Exported Asset 39 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_domestic_39_features.xlsx
Exported Asset 40 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_domestic_40_features.xlsx
Exported Asset 41 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_domestic_41_features.xlsx
Exported Asset 42 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_domestic_42_features.xlsx
Exported Asset 43 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_domestic_43_features.xlsx
Exported Asset 44 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_domestic_44_features.xlsx
Exported Asset 45 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_domestic_45_features.xlsx
Exported Asset 46 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_domestic_46_features.xlsx

In [10]:
roc_periods = [1, 3, 6, 9, 12]
asset_columns = [col for col in weekly_rets.columns if col.startswith('Asset')]

indicators = {
    'ROC': lambda df: calculate_roc(df, roc_periods)
}

asset_dataframes_master_global = {}

for i_investment in range(equity_global_monthly_rets.shape[1]):
    data_in = pd.DataFrame(equity_global.iloc[:, i_investment]).dropna()
    equity_global_monthly_rets_in = pd.DataFrame(equity_global_monthly_rets.loc[data_in.index[0]:])
    columns_in = data_in.columns

    downside_deviation = calculate_downside_deviation_ts(
        data=data_in, 
        rolling_windows=[20, 60, 126, 252, 504], 
        target_return=0
    )

    asset_dataframes_out = apply_indicators_equity_baskets(
        data=equity_global_monthly_rets_in,           # Weekly returns data for each asset
        indicators=indicators,                          # Dictionary of indicators
        assets=columns_in,                              # List of asset columns
        reference_data=data_in                          # Daily return data for indicators calculation
    )

    for asset, asset_df in asset_dataframes_out.items():
        # Add downside deviation for the current asset
        if not downside_deviation.empty:
            downside_dev_cols = [col for col in downside_deviation.columns if asset in col]
            if downside_dev_cols:  # Only add columns if they exist for the current asset
                asset_df = pd.concat([asset_df, downside_deviation[downside_dev_cols]], axis=1)

        for lag in lags:
            lagged_downside_dev = downside_deviation[downside_dev_cols].shift(lag).add_suffix(f"_lag{lag}")
            asset_df = pd.concat([asset_df, lagged_downside_dev], axis=1)

        one_hot_df = pd.DataFrame(0, index=asset_df.index, 
                                  columns=[f'Asset_{i+1}' for i in range(equity_global_monthly_rets.shape[1])])
        one_hot_df[f'Asset_{i_investment + 1}'] = 1  # Set 1 only for the current asset being processed
        asset_df = pd.concat([asset_df, one_hot_df], axis=1)
        asset_df = asset_df.dropna()
        asset_df.columns = [col.replace(f'_{asset}', '') for col in asset_df.columns]
        asset_dataframes_out[asset] = asset_df
    asset_dataframes_master_global[i_investment] = asset_dataframes_out


i_investment = 51
asset_name = 'Asset 52'

asset_dataframes = asset_dataframes_master_global[i_investment]
asset_dataframes['Asset 52']

,MACD_Line,Signal_Line,MACD_Histogram,RSI,Stoch_RSI,SMA20,SMA90,SMA180,SMA240,Upper20,...,Asset_43,Asset_44,Asset_45,Asset_46,Asset_47,Asset_48,Asset_49,Asset_50,Asset_51,Asset_52
Date,,,,,,,,,,,,,,,,,,,,,
2006-05-01,0.0019,0.0057,-0.0038,39.6465,0.0330,1.6747,1.6533,1.6129,1.5889,1.7021,...,0,0,0,0,0,0,0,0,0,1
2006-06-01,-0.0267,-0.0268,0.0001,41.0714,1.0000,1.5921,1.6374,1.6192,1.5979,1.6929,...,0,0,0,0,0,0,0,0,0,1
2006-07-03,-0.0087,-0.0163,0.0076,65.1883,1.0000,1.5201,1.6092,1.6178,1.6003,1.5608,...,0,0,0,0,0,0,0,0,0,1
2006-08-01,-0.0158,-0.0205,0.0047,45.6479,0.9193,1.4626,1.5704,1.6084,1.5918,1.5198,...,0,0,0,0,0,0,0,0,0,1
2006-09-01,0.0185,0.0144,0.0041,81.1321,0.9922,1.5103,1.5281,1.5904,1.5879,1.5857,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-01-03,-0.2133,-0.1558,-0.0574,28.8445,0.1821,12.4964,12.7587,13.2874,13.9110,13.3021,...,0,0,0,0,0,0,0,0,0,1
2023-02-01,0.2673,0.1706,0.0967,73.0974,0.6136,12.8295,12.6102,13.1131,13.6421,13.8102,...,0,0,0,0,0,0,0,0,0,1
2023-03-01,0.0468,0.1483,-0.1015,34.2201,0.0738,13.7031,12.8973,13.1257,13.5250,14.2767,...,0,0,0,0,0,0,0,0,0,1
2023-04-03,0.2608,0.1930,0.0678,76.6043,0.8474,13.9075,13.2266,13.2478,13.3188,14.7656,...,0,0,0,0,0,0,0,0,0,1
2023-04-11,0.2413,0.2345,0.0068,57.6398,0.0000,14.1878,13.3115,13.2719,13.3096,14.8164,...,0,0,0,0,0,0,0,0,0,1

In [11]:
data_path = os.path.dirname(os.getcwd()) + '/data'
os.makedirs(data_path, exist_ok=True)

for i_investment, asset_dataframes_out in asset_dataframes_master_global.items():
    for asset, df in asset_dataframes_out.items():
        filename = os.path.join(data_path, f'equity_global_{i_investment + 1}_features.xlsx')
        df.to_excel(filename, sheet_name=f'{asset}_features', index=True)
        print(f"Exported {asset} to {filename}")

Exported Asset 1 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_global_1_features.xlsx
Exported Asset 2 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_global_2_features.xlsx
Exported Asset 3 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_global_3_features.xlsx
Exported Asset 4 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_global_4_features.xlsx
Exported Asset 5 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_global_5_features.xlsx
Exported Asset 6 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_global_6_features.xlsx
Exported Asset 7 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_global_7_features.xlsx
Exported Asset 8 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_global_8_features.xlsx
Exported Asset 9 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_global_9_features.xlsx
Exported Asset 10 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_global_10_features.xlsx
Exported Asset 11 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_global_11_features.xlsx
Exported Asset 12 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_global_12_features.xlsx
Exported Asset 13 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_global_13_features.xlsx
Exported Asset 14 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_global_14_features.xlsx
Exported Asset 15 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_global_15_features.xlsx
Exported Asset 16 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_global_16_features.xlsx
Exported Asset 17 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_global_17_features.xlsx
Exported Asset 18 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_global_18_features.xlsx
Exported Asset 19 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_global_19_features.xlsx
Exported Asset 20 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_global_20_features.xlsx
Exported Asset 21 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_global_21_features.xlsx
Exported Asset 22 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_global_22_features.xlsx
Exported Asset 23 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_global_23_features.xlsx
Exported Asset 24 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_global_24_features.xlsx
Exported Asset 25 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_global_25_features.xlsx
Exported Asset 26 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_global_26_features.xlsx
Exported Asset 27 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_global_27_features.xlsx
Exported Asset 28 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_global_28_features.xlsx
Exported Asset 29 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_global_29_features.xlsx
Exported Asset 30 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_global_30_features.xlsx
Exported Asset 31 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_global_31_features.xlsx
Exported Asset 32 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_global_32_features.xlsx
Exported Asset 33 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_global_33_features.xlsx
Exported Asset 34 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_global_34_features.xlsx
Exported Asset 35 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_global_35_features.xlsx
Exported Asset 36 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_global_36_features.xlsx
Exported Asset 37 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_global_37_features.xlsx
Exported Asset 38 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_global_38_features.xlsx
Exported Asset 39 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_global_39_features.xlsx
Exported Asset 40 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_global_40_features.xlsx
Exported Asset 41 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_global_41_features.xlsx
Exported Asset 42 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_global_42_features.xlsx
Exported Asset 43 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_global_43_features.xlsx
Exported Asset 44 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_global_44_features.xlsx
Exported Asset 45 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_global_45_features.xlsx
Exported Asset 46 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_global_46_features.xlsx
Exported Asset 47 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_global_47_features.xlsx
Exported Asset 48 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_global_48_features.xlsx
Exported Asset 49 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_global_49_features.xlsx
Exported Asset 50 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_global_50_features.xlsx
Exported Asset 51 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_global_51_features.xlsx
Exported Asset 52 to /Users/a14542/Desktop/UChicago/24 AU/Flexible Plan Investments/fpi_project_lab_autumn2024/data/equity_global_52_features.xlsx